In [1]:
import numpy as np
import scipy.linalg as linalg

In [2]:
# random seed for reproducible results
np.random.seed(1)

In [17]:
my_data = np.genfromtxt('wine_data.csv', delimiter=',')
n_train = 100

np.random.shuffle(my_data)  # shuffle datataset
trainingData = my_data[:n_train, 1:]  # training data
trainingLabels = my_data[:n_train, 0]  # class labels of training data

testData = my_data[n_train:, 1:]  # training data
testLabels = my_data[n_train:, 0]  # class labels of training data

In [18]:
trainingLabels[trainingLabels==3]

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [19]:
trainingLabels.shape

(100,)

In [28]:
train_temp_label=trainingLabels.reshape(-1,1)

In [33]:
index=np.where(train_temp_label==3)[0]

In [51]:
np.where(train_temp_label==3)[0].shape[0]

27

In [11]:
trainingData.shape

(100, 13)

In [45]:
((trainingData[index]-np.mean(trainingData[index],axis=0))@(trainingData[index]-np.mean(trainingData[index],axis=0)).T).shape

(27, 27)

In [40]:
np.mean(trainingData,axis=0)

array([1.30582e+01, 2.35840e+00, 2.37700e+00, 1.95610e+01, 9.97600e+01,
       2.25540e+00, 2.00590e+00, 3.69900e-01, 1.57460e+00, 5.03440e+00,
       9.50460e-01, 2.61280e+00, 7.56210e+02])

In [46]:
a=[1,2,3]

In [62]:
X=trainingData
Y=train_temp_label

In [92]:
classLabels = np.unique(Y)  # different class labels on the dataset
classNum = len(classLabels)
datanum, dim = X.shape  # dimensions of the dataset
totalMean = np.mean(X, 0)  # total mean of the data
s_w=[]
s_b=[]
mean_class=[]



for i in range(classNum):
        index=np.where(Y==(i+1))[0]
        mean=np.mean(X[index],axis=0)
        mean_class.append(mean)
        cov=np.cov(X[index],rowvar=False)
        s_w.append(cov)

cov_total=np.cov(X,rowvar=False)

Sw=sum(s_w)

Sb=cov_total-Sw


        


(13, 13)
(13, 13)


In [216]:
def my_LDA(X, Y):
    """
    Train a LDA classifier from the training set
    X: training data
    Y: class labels of training data

    """    
    classLabels = np.unique(Y)  # different class labels on the dataset
    classNum = len(classLabels)
    datanum, dim = X.shape  # dimensions of the dataset
    totalMean = np.mean(X, 0)  # total mean of the data

    # ====================== YOUR CODE HERE ======================
    # Instructions: Implement the LDA technique, following the
    # steps given in the pseudocode on the assignment.
    # The function should return the projection matrix W,
    # the centroid vector for each class projected to the new
    # space defined by W and the projected data X_lda.
    
    s_w=[]
    s_b=[]
    mean_class=[]
    
    projected_centroid=[]
    
    for i in range(classNum):
        index=np.where(Y==(i+1))[0]
        mean=np.mean(X[index],axis=0)
        mean_class.append(mean)
        cov=np.cov(X[index],rowvar=False)* index.shape[0]
        print(index.shape[0])
        s_w.append(cov)
        

    cov_total=np.cov(X,rowvar=False)

    Sw=sum(s_w)

    Sb=cov_total-Sw
    
    prod=(np.linalg.inv(Sw))@Sb
    
    eig_val,eig_vec=np.linalg.eig(prod)
    
    sort_index=eig_val.argsort()[::-1]
    
    print(eig_vec.shape)
    
    print(eig_vec[:,sort_index].shape)
    
    W=eig_vec[:,sort_index][:,:classNum]
    
    X_lda=X@W
    
    
    for i in mean_class:
        projected_centroid.append(i@W)
    
    
        
    
        
        
        
        


    # =============================================================

    return W, projected_centroid, X_lda

In [217]:
# training LDA classifier
W, projected_centroid, X_lda = my_LDA(trainingData, train_temp_label)

32
41
27
(13, 13)
(13, 13)


In [218]:
W.shape

(13, 3)

In [219]:
len(projected_centroid)

3

In [220]:
projected_centroid[0]

array([-4.99172157,  4.00344543,  0.29987038])

In [221]:
X_lda.shape

(100, 3)

In [222]:
a.index(min(a))

0

In [223]:
for i in X_lda:
    print(i)

[-2.80644165  3.06555995 -0.30665441]
[-1.37919401  4.04221295  0.4119284 ]
[-1.2295032   3.79790907  0.36515443]
[-2.25268068  3.3077336   0.26868525]
[-3.60738804  2.97474152  0.31550695]
[-1.0642116   4.47891402  0.49907672]
[-2.87253252  3.0513767   0.51889649]
[-2.03981918  4.03219592  0.38459763]
[-3.23686126  2.90535997  0.45015695]
[-2.68954579  3.50811063 -0.36261774]
[-3.72906343  2.6932619   0.16364734]
[-4.02722656  3.73369951  0.32789504]
[-5.20117662  4.13668787  0.39010984]
[-1.20216805  4.19084856  0.30669929]
[-2.21128761  3.91960071  0.14616928]
[-0.89625514  4.37652103  0.34055336]
[-2.47804275  4.19269752  0.35189537]
[-1.53592162  4.18009435  0.20073119]
[-5.44643379  4.33673344  0.28498859]
[-3.85972646  3.06346881  0.47878146]
[-4.91585104  3.81945306  0.30699823]
[-3.36925229  2.9074005   0.1962937 ]
[-2.98192554  3.04221559  0.61844713]
[-3.43889111  3.27096937  0.48495213]
[-3.25952768  2.94226085  0.4660006 ]
[-5.61217971  4.35505696  0.39520054]
[-5.33368036

In [224]:
def predict(X, projected_centroid, W):
    """Apply the trained LDA classifier on the test data
    X: test data
    projected_centroid: centroid vectors of each class projected to the new space
    W: projection matrix computed by LDA
    """

    # Project test data onto the LDA space defined by W
    projected_data = np.dot(X, W)

    # ====================== YOUR CODE HERE ======================
    # Instructions: Fill in the code to implement the classification
    # part of LDA. Follow the steps given in the assigment.

    # =============================================================

    # Return the predicted labels of the test data X
    
    label=[]
    
    for i in projected_data:
        temp=[]
        for j in projected_centroid:
            dist=np.linalg.norm(i-j)
            temp.append(dist)
        label.append(temp.index(min(temp)))
            
    return label

In [225]:
# Perform predictions for the test data
predictedLabels = predict(testData, projected_centroid, W)

predictedLabels = [label+1 for label in predictedLabels]
print(predictedLabels)


# Compute accuracy
counter = 0
for i in range(len(predictedLabels)):
    if predictedLabels[i] == testLabels[i]:
        counter += 1
print('Accuracy of LDA: %f' % (counter / float(len(predictedLabels)) * 100.0))

[2, 1, 1, 2, 2, 3, 3, 1, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 3, 3, 2, 3, 3, 2, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 3, 1, 2, 2, 2, 1, 2, 1, 3, 2, 2, 3, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 3, 2, 1, 2, 2, 3, 3, 3, 2, 1, 3, 1, 2, 2, 1, 1, 2, 3]
Accuracy of LDA: 98.717949


In [1]:
from skopt import BayesSearchCV